### PR TITLE
upgrade to OCI SDK v46.2.0, support resource principal

### PR DESCRIPTION
**Pull request by janotav**
# Overview

- Upgrading OCI SDK dependency to latest released version
- Enabling resource principal support

# Design of Change
Dependency upgraded and resulting API incompatibilities resolved.

# Related Issues/Pull Requests
[Implements #11](https://github.com/hashicorp/vault-plugin-auth-oci/issues/11)

# Contributor Checklist
Manual integration test performed in the context of Datascience Notebook:

```
bash-4.2$ ./vault_linux_amd64 login -method=oci auth_type=resource role=vaultadminrole
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                     Value
---                     -----
token                   s.ByVZPV8SjUeUOJGivwXmGNmA
token_accessor          g4grdgoYdGA0QgRzntPTWBfz
token_duration          30m
token_renewable         false
token_policies          ["default" "vaultadminpolicy"]
identity_policies       []
policies                ["default" "vaultadminpolicy"]
token_meta_role_name    vaultadminrole
```

### CODE REVIEW

**Comment by davidkhala** [comment]
LGTM, anyone can help to review?

**Comment by davidkhala** [comment]
> @davidkhala Can you review this and commit please or assign to someone that can commit?

I am not maintainer for this so still waiting for someone else

**Comment by F21** [comment]
Can someone from hashicorp take a look at this? I am currently implementing oci auth for the Vault Agent and it's quite painful to run the end to end tests as the oci auth backend currently only works with Instance Principal credentials, which are only available in OCI compute instances.

**Comment by mattalberts** [comment]
@dhuckins
Trying to find a larger list of maintainers. Is there anything we can go to move this one along? I'm very interested in using the change within OCI

**Comment by raymonstah** [comment]
Closing in favor of https://github.com/hashicorp/vault-plugin-auth-oci/pull/34

**Pull request closed without merging**
